### PR TITLE
Add filter to filter possible redirect matches

### PR DESCRIPTION
**Pull request by diedexx**
As discussed with @tfrommen.

#### What's Included in This Pull Request
* A new filter to filter the redirect matches.

We want to add geolocation to the redirect formula. This filter will allow us to do so.

### CODE REVIEW

**Comment by tfrommen** [comment]
@diedexx I just did some minor changes. Still works for you this way?

**Comment by diedexx** [comment]
@tfrommen Sure, we can work with that. thnx :+1:

**Comment by tfrommen** [comment]
Manually merged into new branch, [`2.7`](https://github.com/inpsyde/MultilingualPress/commits/2.7).

Thanks!

**Comment by tfrommen** [comment]
Hey @diedexx, please be aware that I changed the filter to `multilingualpress.redirect_targets` in order to stay future-proof with the upcoming version 3.

**Pull request closed without merging**
